# Generated by Django 6.0.1 on 2026-02-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_game', '0002_mafiaquestion_question_mafiaanswer_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='name',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey_game.poll'),
            preserve_default=False,
        ),
    ]
