# Generated by Django 6.0.1 on 2026-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_game', '0003_rename_question_poll_name_question_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
            preserve_default=False,
        ),
    ]
