# Generated by Django 6.0.1 on 2026-02-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_game', '0004_remove_useranswer_answer_text_useranswer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mafiaanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mafiaanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='MafiaQuestion',
        ),
        migrations.DeleteModel(
            name='MafiaAnswer',
        ),
    ]
