# Generated by Django 6.0.1 on 2026-02-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_game', '0005_remove_mafiaanswer_question_remove_mafiaanswer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
